
project_id = "pdlqxpckrxrsfyuknsjg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = true

[edge_functions]
[edge_functions.withdrawal-requests]
verify_jwt = true

[edge_functions.create-razorpay-order]
verify_jwt = true

[edge_functions.verify-razorpay-payment]
verify_jwt = true

[edge_functions.admin-dashboard-data]
verify_jwt = false

[edge_functions.delete-user-content]
verify_jwt = true
