// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfvlxnlywzfzelcwccfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmdmx4bmx5d3pmemVsY3djY2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzYyMDAsImV4cCI6MjA2MTM1MjIwMH0.l-Nc6cpU8c6ojHOO-XwkJIn5On9dItiIlEpbZ5O5qDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);